[package]
name = "nixdoc"
version = "0.1.0"
authors = ["Vincent Ambo <mail@tazj.in>"]

[dependencies]
xml-rs = "0.8"
structopt = "0.2"
failure = "0.1"

[dependencies.rnix]
git = "https://gitlab.com/jD91mZM2/rnix"
branch = "stable"
