[package]
name = "nixdoc"
version = "2.2.0"
authors = ["Vincent Ambo <mail@tazj.in>", "asymmetric"]

[dependencies]
xml-rs = "0.8"
structopt = "0.2"
failure = "0.1"
rnix = "0.11"
rowan = "0.15.11"
textwrap = "0.16"

[dev-dependencies]
insta = "1.29.0"
